apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URL: {{ .Values.backend.env.MONGO_URL | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
  JWT_EXPIRES_IN: {{ .Values.backend.env.JWT_EXPIRES_IN | quote }}
